services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      APACHE_DISABLE_REWRITE: "false"
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_DATA_DIR: "/mnt/data"
      TZ: ${TZ}
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 127.0.0.1
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - ${USERDIR}/docker/nextcloud/data:/mnt/data
      - /var/run/docker.sock:/var/run/docker.sock
    shm_size: 512m

volumes: # If you want to store the data on a different drive, see https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
